name: 'Deploy pipeline'

on:
  # run each merge to main branch
  push:
    branches:
      - main
      - dev
      - release/*
  
permissions:
  id-token: write # required for OIDC authentication
  contents: write # ensures the token can write repository content

env:
  NODE_VERSION: '18.x'
  GH_ASSUME_ROLE: 'GitHubActionsAssumeRole'
  DEV_AWS_ACCOUNT_ID: '166669426596'
  PROD_AWS_ACCOUNT_ID: '173381260310'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Initial Setup
        uses: ./.github/actions/initial-setup
        with:
          node_version: $NODE_VERSION
          environment: 'dev' # TODO: change to matrix or variable per branch
          prod_aws_account_id: $PROD_AWS_ACCOUNT_ID
          dev_aws_account_id: $DEV_AWS_ACCOUNT_ID
          gh_assume_role: $GH_ASSUME_ROLE

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: npm-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            npm-${{ runner.os }}-
      
      - name: Install dependencies
        run: npm ci

      - name: Run ESLint
        run: npm run lint

      - name: Run Tests & Generate Coverage
        run: npm run test:ci

      - name: Run Build
        run: npm run build

      - name: Deploy Build And Reset CloudFront Cache
        run: |
          echo "S3 deploy..."
          echo "CDN cache reset..."
