name: 'Deploy pipeline'

on:
  # run each merge to deployment env branches
  push:
    branches:
      - main
      - develop
      - release/**
  # manual trigger
  workflow_dispatch:
    inputs:
      environment:
        description: 'Target environment'
        type: choice
        required: true
        options:
          - dev
          - uat
          - prod
      branch:
        description: 'Branch to deploy'
        type: choice
        required: true
        options:
          - develop
          - main
      custom_branch:
        description: 'Release branch name (for UAT and Prod deployments)'
        type: string
        required: false

permissions:
  id-token: write # required for OIDC authentication
  contents: write # ensures the token can write repository content

env:
  NODE_VERSION: '18.x'
  TARGET_ENV: 'dev'
  GH_ASSUME_ROLE: 'GitHubActionsAssumeRole'
  DEV_AWS_ACCOUNT_ID: '166669426596'
  UAT_AWS_ACCOUNT_ID: '166669426596'
  PROD_AWS_ACCOUNT_ID: '173381260310'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: >-
            ${{ github.event.inputs.custom_branch && github.event.inputs.custom_branch != '' && github.event.inputs.custom_branch || github.event.inputs.branch || github.ref_name }}

      - name: Validate Deployment Eligibility
        run: |
          TARGET_ENV="${{ github.event.inputs.environment }}"
          DEPLOY_BRANCH="${{ github.event.inputs.branch }}"
          CUSTOM_BRANCH="${{ github.event.inputs.custom_branch }}"
          GIT_REF="${{ github.ref_name }}"

          # Decide the target branch (prefer custom_branch if set, fallback to git ref from a push event)
          if [[ ! -z "$CUSTOM_BRANCH" ]]; then
            DEPLOY_BRANCH="$CUSTOM_BRANCH"
          elif [[ ! -z "$DEPLOY_BRANCH" ]]; then
            DEPLOY_BRANCH="$DEPLOY_BRANCH"
          else
            DEPLOY_BRANCH="$GIT_REF"
          fi

          # Determine default environment (fallback to dev/uat based on branch if from a push event)
          if [[ -z "$TARGET_ENV" ]]; then
            if [[ "$DEPLOY_BRANCH" == "develop" ]]; then
              TARGET_ENV="dev"
            elif [[ "$DEPLOY_BRANCH" == "main" || "$DEPLOY_BRANCH" =~ ^release/ ]]; then
              TARGET_ENV="uat"
            fi
          fi

          # Additional validation rules
          if [[ "$TARGET_ENV" == "dev" ]]; then
            # dev: use develop by default, fallback to custom_branch if it exists
            if [[ "$DEPLOY_BRANCH" != "develop" && -z "$CUSTOM_BRANCH" ]]; then
              echo "ERROR: For 'dev' environment, use 'develop' branch or provide a valid custom_branch!"
              exit 1
            fi
          elif [[ "$TARGET_ENV" == "uat" ]]; then
            # uat: use main/release/x by default, fallback to custom_branch if it exists
            if [[ "$DEPLOY_BRANCH" != "main" && ! "$DEPLOY_BRANCH" =~ ^release/ && -z "$CUSTOM_BRANCH" ]]; then
              echo "ERROR: For 'uat' environment, use 'main'/'release/x' branch or provide a valid custom_branch!"
              exit 1
            fi
          elif [[ "$TARGET_ENV" == "prod" ]]; then
            # prod: only custom_branch set and must match release/x*
            if [[ -z "$CUSTOM_BRANCH" ]]; then
              echo "ERROR: For 'prod', custom_branch must be provided and must match release/x* format!"
              exit 1
            fi
            if [[ ! "$CUSTOM_BRANCH" =~ ^release/ ]]; then
              echo "ERROR: For 'prod', custom_branch must match release/x* format!"
              exit 1
            fi
            DEPLOY_BRANCH="$CUSTOM_BRANCH"
          fi

          echo "Deploying branch '${DEPLOY_BRANCH}' to '${TARGET_ENV}' environment.."
          echo "TARGET_ENV=$TARGET_ENV" >> $GITHUB_ENV
          echo "DEPLOY_BRANCH=$DEPLOY_BRANCH" >> $GITHUB_ENV

      - name: Initial Setup
        uses: ./.github/actions/initial-setup
        with:
          node_version: ${{ env.NODE_VERSION }}
          environment: ${{ env.TARGET_ENV }}
          prod_aws_account_id: ${{ env.PROD_AWS_ACCOUNT_ID }}
          uat_aws_account_id: ${{ env.PROD_AWS_ACCOUNT_ID }}
          dev_aws_account_id: ${{ env.DEV_AWS_ACCOUNT_ID }}
          gh_assume_role: ${{ env.GH_ASSUME_ROLE }}

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: npm-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            npm-${{ runner.os }}-
      
      - name: Install Dependencies
        run: npm ci

      - name: Run ESLint
        run: npm run lint

      - name: Run CI non-interactive tests (JUnit output)
        run: npm run test:ci
        env:
          JEST_JUNIT_OUTPUT_DIR: ./junit
          JEST_JUNIT_OUTPUT_NAME: junit.xml

      - name: Run Build
        run: npm run build

      - name: Deploy Build And Reset CloudFront Cache
        run: |
          echo "S3 deploy..."
          ls -al build/

          echo "CDN cache reset..."
          aws --version
          aws sts get-caller-identity
