name: 'Pull Request Teardown pipeline'

on:
  pull_request:
    types: [closed]
  
permissions:
  id-token: write # required for OIDC authentication
  contents: write # ensures the token can write repository content
  pull-requests: write # required for reviewdog to post PR comments

jobs:
  pr-teardown:
    runs-on: ubuntu-latest
    environment: preview
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout Repository
        id: checkout
        uses: actions/checkout@v4
      
      - name: AWS Credentials Setup
        id: aws-credentials-setup
        uses: ./.github/actions/aws-credentials-setup
        with:          
          aws_account_id: ${{ vars.AWS_ACCOUNT_ID }}
          gh_assume_role: ${{ vars.GH_ASSUME_ROLE }}
          deploy_role: ${{ vars.DEPLOY_ROLE }}
          environment: ${{ github.job.environment }}

      - name: Preview Environment Teardown
        id: teardown
        uses: ./.github/actions/delete-preview-environment
        with:
          aws_account_id: ${{ vars.AWS_ACCOUNT_ID }}
          gh_assume_role: ${{ vars.GH_ASSUME_ROLE }}
          environment: ${{ github.job.environment }}
          s3_bucket: ${{ vars.S3_BUCKET_NAME }}
          cloudfront_distribution_id: ${{ vars.CLOUDFRONT_DISTRIBUTION_ID }}
          pr_number: ${{ github.event.pull_request.number }}
