name: 'Pull Request pipeline'

on:
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]
  
permissions:
  id-token: write # required for OIDC authentication
  contents: write # ensures the token can write repository content
  pull-requests: write # required for reviewdog to post PR comments

jobs:
  pr-validate:
    runs-on: ubuntu-latest
    environment: preview
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout Repository
        id: checkout
        uses: actions/checkout@v4

      - name: Setup Node.js from .nvmrc
        id: setup-node
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc

      - name: Setup ReviewDog
        id: setup-reviewdog
        uses: reviewdog/action-setup@v1.5.0
        with:
          reviewdog_version: latest
      
      - name: AWS Credentials Setup
        id: aws-credentials-setup
        uses: ./.github/actions/aws-credentials-setup
        with:          
          aws_account_id: ${{ vars.AWS_ACCOUNT_ID }}
          gh_assume_role: ${{ vars.GH_ASSUME_ROLE }}
          deploy_role: ${{ vars.DEPLOY_ROLE }}
          environment: ${{ github.job.environment }}

      - name: Preparations and Quality Gates
        id: quality-gates
        uses: ./.github/actions/install-quality-gates-setup

      - name: Run Build
        id: build
        run: PUBLIC_URL=/preview-envs/PR-${{ github.event.pull_request.number }}/npm run build

      - name: Deploy Preview Environment
        id: deploy
        uses: ./.github/actions/deploy-to-aws
        with:
          aws_account_id: ${{ vars.AWS_ACCOUNT_ID }}
          gh_assume_role: ${{ vars.GH_ASSUME_ROLE }}
          environment: ${{ github.job.environment }}
          environment_url: ${{ vars.ENVIRONMENT_URL }}
          s3_bucket: ${{ vars.S3_BUCKET_NAME }}
          cloudfront_distribution_id: ${{ vars.CLOUDFRONT_DISTRIBUTION_ID }}
          pr_number: ${{ github.event.pull_request.number }}

      - name: Comment Preview URL on PR
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr comment --edit-last ${{ github.event.pull_request.number }} --body "ðŸš€ Preview environment URL: [${{ steps.deploy.outputs.env_url }}](${{ steps.deploy.outputs.env_url }})"
