name: 'Pull Request pipeline'

on:
  # run each Pull Request is opened  
  pull_request:
  
permissions:
  id-token: write # required for OIDC authentication
  contents: write # ensures the token can write repository content
  pull-requests: write # required for reviewdog to post PR comments

env:
  NODE_VERSION: '18.x'
  TARGET_ENV: 'dev'
  GH_ASSUME_ROLE: 'GitHubActionsAssumeRole'
  PROD_AWS_ACCOUNT_ID: '173381260310'
  UAT_AWS_ACCOUNT_ID: '166669426596'
  DEV_AWS_ACCOUNT_ID: '166669426596'

jobs:
  validate:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Initial Setup
        uses: ./.github/actions/initial-setup
        with:
          node_version: ${{ env.NODE_VERSION }}
          environment: 'dev'
          prod_aws_account_id: ${{ env.PROD_AWS_ACCOUNT_ID }}
          uat_aws_account_id: ${{ env.UAT_AWS_ACCOUNT_ID }}
          dev_aws_account_id: ${{ env.DEV_AWS_ACCOUNT_ID }}
          gh_assume_role: ${{ env.GH_ASSUME_ROLE }}

      - name: Preparations and Quality Gates
        uses: ./.github/actions/install-quality-gates-setup
