name: 'Pull Request pipeline'

on:
  # run each Pull Request is opened  
  pull_request:
  
permissions:
  id-token: write # required for OIDC authentication
  contents: write # ensures the token can write repository content
  pull-requests: write # required for reviewdog to post PR comments

jobs:
  validate:
    runs-on: ubuntu-latest
    environment: preview
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Initial Setup
        uses: ./.github/actions/initial-setup
        with:          
          aws_account_id: ${{ vars.AWS_ACCOUNT_ID }}
          gh_assume_role: ${{ vars.GH_ASSUME_ROLE }}
          environment: ${{ github.job.environment }}

      - name: Preparations and Quality Gates
        uses: ./.github/actions/install-quality-gates-setup
