name: 'Pull Request pipeline'

on:
  # run each Pull Request is opened  
  pull_request:
  
permissions:
  id-token: write # required for OIDC authentication
  contents: write # ensures the token can write repository content
  pull-requests: write # required for reviewdog to post PR comments

jobs:
  pr-validate:
    runs-on: ubuntu-latest
    environment: preview
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout Repository
        id: checkout
        uses: actions/checkout@v4
      
      - name: Initial Setup
        id: initial-setup
        uses: ./.github/actions/initial-setup
        with:          
          aws_account_id: ${{ vars.AWS_ACCOUNT_ID }}
          gh_assume_role: ${{ vars.GH_ASSUME_ROLE }}
          environment: ${{ github.job.environment }}

      - name: Preparations and Quality Gates
        id: quality-gates
        uses: ./.github/actions/install-quality-gates-setup

      - name: Run Build
        id: build
        run: npm run build

      - name: Deploy Preview Environment
        id: deploy
        uses: ./.github/actions/deploy-to-aws
        with:
          aws_account_id: ${{ vars.AWS_ACCOUNT_ID }}
          gh_assume_role: ${{ vars.GH_ASSUME_ROLE }}
          environment: ${{ github.job.environment }}
          environment_url: ${{ vars.ENVIRONMENT_URL }}
          s3_bucket: ${{ vars.S3_BUCKET_NAME }}
          cloudfront_distribution_id: ${{ vars.CLOUDFRONT_DISTRIBUTION_ID }}
          pr_number: ${{ github.event.pull_request.number }}

      - name: Comment Preview URL on PR
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr comment ${{ github.event.pull_request.number }} --body "ðŸš€ Preview environment URL: [${{ steps.deploy.outputs.env_url }}](${{ steps.deploy.outputs.env_url }})"
