name: 'Pull Request pipeline'

on:
  # run each Pull Request is opened  
  pull_request:
  
permissions:
  id-token: write # required for OIDC authentication
  contents: write # ensures the token can write repository content
  pull-requests: write # required for reviewdog to post PR comments

env:
  NODE_VERSION: '18.x'
  GH_ASSUME_ROLE: 'GitHubActionsAssumeRole'
  DEV_AWS_ACCOUNT_ID: '166669426596'
  PROD_AWS_ACCOUNT_ID: '173381260310'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Initial Setup
        uses: ./.github/actions/initial-setup
        with:
          node_version: ${{ env.NODE_VERSION }}
          environment: 'dev' # TODO: change to matrix or variable per branch
          prod_aws_account_id: ${{ env.PROD_AWS_ACCOUNT_ID }}
          dev_aws_account_id: ${{ env.DEV_AWS_ACCOUNT_ID }}
          gh_assume_role: ${{ env.GH_ASSUME_ROLE }}

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: npm-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            npm-${{ runner.os }}-
      
      - name: Install Dependencies
        run: npm ci

      - name: Run ESLint
        run: npm run lint

      - name: Report ESLint with ReviewDog
        if: always()
        run: |
          npm run lint -- --format checkstyle | npx reviewdog -f=checkstyle -name="eslint" -reporter=github-pr-review -fail-level=warning
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ github.token }} # for reviewdog rate-limiting

      - name: Run CI non-interactive tests (JUnit output)
        run: npm run test:ci
        env:
          JEST_JUNIT_OUTPUT_DIR: ./junit
          JEST_JUNIT_OUTPUT_NAME: junit.xml
